'-------------------------------------------------------------------------------
'-- VBS-Script-Datei
'-- Neu erstellt am 01.10.2008 08:10:36
'-- Ersteller: 
'-- Kommentar: 
'-------------------------------------------------------------------------------
Option Explicit  'Erzwingt die explizite Deklaration aller Variablen in einem Skript.

 Call UserVarCompile("gvar_eva_abb_v1.6.vas")

call sel_doc_string("test","doc_string_ing_","","","")
'msgbox maxord("doc_string_ing_")